/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SnapBountyEscrow {
  export type BountyStruct = {
    creator: AddressLike;
    hunter: AddressLike;
    reward: BigNumberish;
    status: BigNumberish;
    proofHash: BytesLike;
    deadline: BigNumberish;
    createdAt: BigNumberish;
    claimedAt: BigNumberish;
  };

  export type BountyStructOutput = [
    creator: string,
    hunter: string,
    reward: bigint,
    status: bigint,
    proofHash: string,
    deadline: bigint,
    createdAt: bigint,
    claimedAt: bigint
  ] & {
    creator: string;
    hunter: string;
    reward: bigint;
    status: bigint;
    proofHash: string;
    deadline: bigint;
    createdAt: bigint;
    claimedAt: bigint;
  };
}

export interface SnapBountyEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "MAX_FEE_BPS"
      | "activeClaim"
      | "approveWork"
      | "bounties"
      | "bountyCount"
      | "cancelBounty"
      | "claimBounty"
      | "createBounty"
      | "getActiveClaim"
      | "getBounty"
      | "isExpired"
      | "owner"
      | "platformFeeBps"
      | "rejectWork"
      | "releaseClaim"
      | "setPlatformFee"
      | "setTreasury"
      | "submitWork"
      | "transferOwnership"
      | "treasury"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BountyCancelled"
      | "BountyClaimed"
      | "BountyCreated"
      | "ClaimReleased"
      | "FeeUpdated"
      | "OwnershipTransferred"
      | "TreasuryUpdated"
      | "WorkApproved"
      | "WorkRejected"
      | "WorkSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeClaim",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveWork",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bounties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bountyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBounty",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveClaim",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rejectWork",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWork",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveWork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bounties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bountyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBounty", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isExpired", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rejectWork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitWork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace BountyCancelledEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    creator: AddressLike,
    refundAmount: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: bigint,
    creator: string,
    refundAmount: bigint
  ];
  export interface OutputObject {
    bountyId: bigint;
    creator: string;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyClaimedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    hunter: AddressLike,
    claimedAt: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: bigint,
    hunter: string,
    claimedAt: bigint
  ];
  export interface OutputObject {
    bountyId: bigint;
    hunter: string;
    claimedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCreatedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    creator: AddressLike,
    reward: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: bigint,
    creator: string,
    reward: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    bountyId: bigint;
    creator: string;
    reward: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimReleasedEvent {
  export type InputTuple = [bountyId: BigNumberish, hunter: AddressLike];
  export type OutputTuple = [bountyId: bigint, hunter: string];
  export interface OutputObject {
    bountyId: bigint;
    hunter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkApprovedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    hunter: AddressLike,
    payout: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: bigint,
    hunter: string,
    payout: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    bountyId: bigint;
    hunter: string;
    payout: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkRejectedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    hunter: AddressLike,
    reason: string
  ];
  export type OutputTuple = [bountyId: bigint, hunter: string, reason: string];
  export interface OutputObject {
    bountyId: bigint;
    hunter: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkSubmittedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    hunter: AddressLike,
    proofHash: BytesLike
  ];
  export type OutputTuple = [
    bountyId: bigint,
    hunter: string,
    proofHash: string
  ];
  export interface OutputObject {
    bountyId: bigint;
    hunter: string;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SnapBountyEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): SnapBountyEscrow;
  waitForDeployment(): Promise<this>;

  interface: SnapBountyEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  MAX_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  activeClaim: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  approveWork: TypedContractMethod<
    [bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  bounties: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, string, bigint, bigint, bigint] & {
        creator: string;
        hunter: string;
        reward: bigint;
        status: bigint;
        proofHash: string;
        deadline: bigint;
        createdAt: bigint;
        claimedAt: bigint;
      }
    ],
    "view"
  >;

  bountyCount: TypedContractMethod<[], [bigint], "view">;

  cancelBounty: TypedContractMethod<
    [bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimBounty: TypedContractMethod<
    [bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createBounty: TypedContractMethod<
    [reward: BigNumberish, deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getActiveClaim: TypedContractMethod<[hunter: AddressLike], [bigint], "view">;

  getBounty: TypedContractMethod<
    [bountyId: BigNumberish],
    [SnapBountyEscrow.BountyStructOutput],
    "view"
  >;

  isExpired: TypedContractMethod<[bountyId: BigNumberish], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  rejectWork: TypedContractMethod<
    [bountyId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  releaseClaim: TypedContractMethod<
    [bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  submitWork: TypedContractMethod<
    [bountyId: BigNumberish, proofHash: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeClaim"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveWork"
  ): TypedContractMethod<[bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bounties"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, string, bigint, bigint, bigint] & {
        creator: string;
        hunter: string;
        reward: bigint;
        status: bigint;
        proofHash: string;
        deadline: bigint;
        createdAt: bigint;
        claimedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bountyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelBounty"
  ): TypedContractMethod<[bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimBounty"
  ): TypedContractMethod<[bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createBounty"
  ): TypedContractMethod<
    [reward: BigNumberish, deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveClaim"
  ): TypedContractMethod<[hunter: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBounty"
  ): TypedContractMethod<
    [bountyId: BigNumberish],
    [SnapBountyEscrow.BountyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isExpired"
  ): TypedContractMethod<[bountyId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rejectWork"
  ): TypedContractMethod<
    [bountyId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseClaim"
  ): TypedContractMethod<[bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitWork"
  ): TypedContractMethod<
    [bountyId: BigNumberish, proofHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BountyCancelled"
  ): TypedContractEvent<
    BountyCancelledEvent.InputTuple,
    BountyCancelledEvent.OutputTuple,
    BountyCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BountyClaimed"
  ): TypedContractEvent<
    BountyClaimedEvent.InputTuple,
    BountyClaimedEvent.OutputTuple,
    BountyClaimedEvent.OutputObject
  >;
  getEvent(
    key: "BountyCreated"
  ): TypedContractEvent<
    BountyCreatedEvent.InputTuple,
    BountyCreatedEvent.OutputTuple,
    BountyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimReleased"
  ): TypedContractEvent<
    ClaimReleasedEvent.InputTuple,
    ClaimReleasedEvent.OutputTuple,
    ClaimReleasedEvent.OutputObject
  >;
  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WorkApproved"
  ): TypedContractEvent<
    WorkApprovedEvent.InputTuple,
    WorkApprovedEvent.OutputTuple,
    WorkApprovedEvent.OutputObject
  >;
  getEvent(
    key: "WorkRejected"
  ): TypedContractEvent<
    WorkRejectedEvent.InputTuple,
    WorkRejectedEvent.OutputTuple,
    WorkRejectedEvent.OutputObject
  >;
  getEvent(
    key: "WorkSubmitted"
  ): TypedContractEvent<
    WorkSubmittedEvent.InputTuple,
    WorkSubmittedEvent.OutputTuple,
    WorkSubmittedEvent.OutputObject
  >;

  filters: {
    "BountyCancelled(uint256,address,uint256)": TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;
    BountyCancelled: TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;

    "BountyClaimed(uint256,address,uint256)": TypedContractEvent<
      BountyClaimedEvent.InputTuple,
      BountyClaimedEvent.OutputTuple,
      BountyClaimedEvent.OutputObject
    >;
    BountyClaimed: TypedContractEvent<
      BountyClaimedEvent.InputTuple,
      BountyClaimedEvent.OutputTuple,
      BountyClaimedEvent.OutputObject
    >;

    "BountyCreated(uint256,address,uint256,uint256)": TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;
    BountyCreated: TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;

    "ClaimReleased(uint256,address)": TypedContractEvent<
      ClaimReleasedEvent.InputTuple,
      ClaimReleasedEvent.OutputTuple,
      ClaimReleasedEvent.OutputObject
    >;
    ClaimReleased: TypedContractEvent<
      ClaimReleasedEvent.InputTuple,
      ClaimReleasedEvent.OutputTuple,
      ClaimReleasedEvent.OutputObject
    >;

    "FeeUpdated(uint256,uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "WorkApproved(uint256,address,uint256,uint256)": TypedContractEvent<
      WorkApprovedEvent.InputTuple,
      WorkApprovedEvent.OutputTuple,
      WorkApprovedEvent.OutputObject
    >;
    WorkApproved: TypedContractEvent<
      WorkApprovedEvent.InputTuple,
      WorkApprovedEvent.OutputTuple,
      WorkApprovedEvent.OutputObject
    >;

    "WorkRejected(uint256,address,string)": TypedContractEvent<
      WorkRejectedEvent.InputTuple,
      WorkRejectedEvent.OutputTuple,
      WorkRejectedEvent.OutputObject
    >;
    WorkRejected: TypedContractEvent<
      WorkRejectedEvent.InputTuple,
      WorkRejectedEvent.OutputTuple,
      WorkRejectedEvent.OutputObject
    >;

    "WorkSubmitted(uint256,address,bytes32)": TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
    WorkSubmitted: TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
  };
}
